version: '2.1'
services:
 audit-db:
    build:
      context: ./db
    command: postgres -c max_connections=1000 -c shared_buffers='512MB'
    networks: 
    - my-net

networks:
  my-net:
    driver: bridge
