version: '2'
services:
  audit-db:
    build:
      context: ./db
  audit-server:
    build:
      context: .
    ports:
    - "44417:44417"
    links:
    - audit-db
    volumes:
    - /home/geoff/go/src/github.com/moonshot-trading/audit-server/log:/go/src/github.com/moonshot-trading/audit-server/log

